FROM nvcr.io/nvidia/l4t-pytorch:r32.5.0-pth1.7-py3

SHELL [ "/bin/bash", "-c" ]

RUN apt-get update && apt-get install -y \
    python3 \
    python3-dev \
    python3-pip

RUN pip3 install --upgrade pip \
    && pip3 install \
    plac \
    opencv-python \
    pandas \
    requests \
    PyYAML \
    tqdm \
    matplotlib \
    seaborn
